<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- src/Bermuda -->
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3240.44" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageVersion Include="WPF-UI" Version="4.2.0" />

    <!-- src/Bermuda.Api -->
    <PackageVersion Include="HotChocolate.AspNetCore" Version="16.6.1" />
    <PackageVersion Include="HotChocolate.Types" Version="16.6.1" />

    <!-- src/Bermuda.AppHost -->
    <PackageVersion Include="Aspire.Hosting.JavaScript" Version="13.5.3" />

    <!-- src/Bermuda.IpcContract.SourceGenerator -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />

    <!-- src/Bermuda.ServiceDefaults -->
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.1.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
  </ItemGroup>

</Project>
