using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bermuda.IpcContract.SourceGenerator;

/// <summary>
/// Discovers <see cref="IpCommandAttribute"/> and <see cref="IpcHostObjectAttribute"/>
/// declarations and the C# record types they reference, maps them to TypeScript,
/// and emits:
///   • the file named by the consuming project's <c>IpcOutputPath</c> MSBuild
///     property (typically <c>src/__generated__/ipc.d.ts</c> in the frontend), and
///   • an embedded <c>internal const string</c> as a compile-time safety net.
///
/// [IpCommand] marks a command on the <c>invoke()</c> postMessage channel and
/// lives on a marker type in Bermuda.IpcContract (referenced assembly).
/// [IpcHostObject] marks a class projected into script via
/// <c>CoreWebView2.AddHostObjectToScript</c> — WebView2 maps its public methods
/// and properties 1:1 onto identically named promises, so those classes live in
/// the *consuming* project (e.g. Bermuda.WindowScriptHost) and are discovered
/// directly off the compilation being generated for.
/// [IpcType] marks a record in Bermuda.IpcContract whose shape should be
/// emitted even though nothing else references it — e.g. one a hand-written TS
/// helper assembles from several host-object members (see IpcTypeAttribute's
/// doc comment for why).
/// </summary>
[Generator]
public sealed class IpcTypesSourceGenerator : IIncrementalGenerator
{
    private const string ContractAssemblyName = "Bermuda.IpcContract";
    private const string OutputPathProperty = "build_property.IpcOutputPath";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var outputPath = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) => provider.GlobalOptions.TryGetValue(OutputPathProperty, out var path) ? path : null);

        var source = context.CompilationProvider.Combine(outputPath);

        context.RegisterSourceOutput(source, static (spc, pair) => Execute(pair.Left, pair.Right, spc));
    }

    private static void Execute(Compilation compilation, string? outputPath, SourceProductionContext context)
    {
        var commands = DiscoverCommands(compilation);
        var hostObjects = DiscoverHostObjects(compilation);
        var (types, enums) = DiscoverTypes(compilation, commands);
        if (commands.Count == 0 && hostObjects.Count == 0 && types.Count == 0 && enums.Count == 0)
            return;

        var ts = TypeScriptDefinition.Build(commands, types, enums, hostObjects);

        // Embedded copy so the .NET build fails loudly if generation is misconfigured.
        var constSource =
            "// <auto-generated>\n" +
            "//   Generated by IpcTypesSourceGenerator. Do not edit.\n" +
            "// </auto-generated>\n" +
            "namespace Bermuda.IpcContract;\n\n" +
            "internal static class IpcTsDefinition\n" +
            "{\n" +
            "    public const string Definition = \"" + EscapeCs(ts) + "\";\n" +
            "}\n";
        context.AddSource("IpcTsDefinition.g.cs", SourceText.From(constSource, Encoding.UTF8));

        if (!string.IsNullOrWhiteSpace(outputPath))
        {
            try
            {
                var full = Path.GetFullPath(outputPath!);
                Directory.CreateDirectory(Path.GetDirectoryName(full)!);
                File.WriteAllText(full, ts);
            }
            catch
            {
                // Generation must never break the build.
            }
        }
    }

    private static string EscapeCs(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r\n", "\\n").Replace("\n", "\\n");

    private static List<CommandInfo> DiscoverCommands(Compilation compilation)
    {
        var results = new List<CommandInfo>();

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            if (assembly.Name != ContractAssemblyName) continue;

            WalkNamespace(assembly.GlobalNamespace, results);
        }

        results.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.Ordinal));
        return results;
    }

    /// <summary>
    /// Types get emitted either because a command's Input/Output names them, or
    /// because they're directly marked [IpcType] (a shape with no single command
    /// or host-object member behind it — e.g. one a TS helper assembles by hand).
    /// </summary>
    private static (List<TypeDefinition> Types, List<EnumDefinition> Enums) DiscoverTypes(
        Compilation compilation, IReadOnlyList<CommandInfo> commands)
    {
        var names = new List<string>(commands
            .SelectMany(c => new[] { c.Input, c.Output })
            .Where(t => t is not "undefined" and not "void"));

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            if (assembly.Name != ContractAssemblyName) continue;

            WalkNamespaceForIpcTypeNames(assembly.GlobalNamespace, names);
        }

        var types = new List<TypeDefinition>();
        var enums = new List<EnumDefinition>();
        foreach (var name in names.Distinct(System.StringComparer.Ordinal))
        {
            var symbol = compilation.GetTypeByMetadataName($"{ContractAssemblyName}.{name}");
            if (symbol is not INamedTypeSymbol type) continue;

            if (type.TypeKind == TypeKind.Enum)
                enums.Add(new EnumDefinition(name, TypeScriptDefinition.MapEnum(type)));
            else
                types.Add(new TypeDefinition(name, TypeScriptDefinition.MapRecord(type)));
        }

        types.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.Ordinal));
        enums.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.Ordinal));
        return (types, enums);
    }

    private static void WalkNamespaceForIpcTypeNames(INamespaceSymbol ns, List<string> acc)
    {
        foreach (var member in ns.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol sub:
                    WalkNamespaceForIpcTypeNames(sub, acc);
                    break;
                case INamedTypeSymbol type when type.GetAttributes().Any(a => a.AttributeClass?.Name == "IpcTypeAttribute"):
                    acc.Add(type.Name);
                    break;
            }
        }
    }

    private static void WalkNamespace(INamespaceSymbol ns, List<CommandInfo> acc)
    {
        foreach (var member in ns.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol sub:
                    WalkNamespace(sub, acc);
                    break;
                case INamedTypeSymbol type:
                    var attribute = type.GetAttributes()
                        .FirstOrDefault(a => a.AttributeClass?.Name == "IpCommandAttribute");
                    if (attribute is null || attribute.ConstructorArguments.Length < 3) continue;

                    var name = (string?)attribute.ConstructorArguments[0].Value;
                    var input = (string?)attribute.ConstructorArguments[1].Value;
                    var output = (string?)attribute.ConstructorArguments[2].Value;
                    var description = attribute.ConstructorArguments.Length > 3
                        ? (string?)attribute.ConstructorArguments[3].Value
                        : "";

                    if (name is null || input is null || output is null) continue;

                    acc.Add(new CommandInfo(name, input, output, description ?? ""));
                    break;
            }
        }
    }

    /// <summary>
    /// Host objects are declared in the project being compiled (e.g. Bermuda's
    /// own WindowScriptHost), not in the referenced contract assembly, so this
    /// walks the compilation's own namespace tree instead of a referenced one.
    /// </summary>
    private static List<HostObjectInfo> DiscoverHostObjects(Compilation compilation)
    {
        var results = new List<HostObjectInfo>();
        WalkNamespaceForHostObjects(compilation.Assembly.GlobalNamespace, results);
        results.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.Ordinal));
        return results;
    }

    private static void WalkNamespaceForHostObjects(INamespaceSymbol ns, List<HostObjectInfo> acc)
    {
        foreach (var member in ns.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol sub:
                    WalkNamespaceForHostObjects(sub, acc);
                    break;
                case INamedTypeSymbol type:
                    var attribute = type.GetAttributes()
                        .FirstOrDefault(a => a.AttributeClass?.Name == "IpcHostObjectAttribute");
                    if (attribute is null || attribute.ConstructorArguments.Length < 1) continue;

                    var name = (string?)attribute.ConstructorArguments[0].Value;
                    if (name is null) continue;

                    acc.Add(BuildHostObjectInfo(name, type));
                    break;
            }
        }
    }

    private static HostObjectInfo BuildHostObjectInfo(string name, INamedTypeSymbol type)
    {
        var properties = new List<HostObjectPropertyInfo>();
        var methods = new List<HostObjectMethodInfo>();

        foreach (var member in type.GetMembers())
        {
            if (member.DeclaredAccessibility != Accessibility.Public || member.IsStatic) continue;

            switch (member)
            {
                case IPropertySymbol property when !property.IsIndexer:
                    properties.Add(new HostObjectPropertyInfo(property.Name, TypeScriptDefinition.MapType(property.Type)));
                    break;

                case IMethodSymbol method when method.MethodKind == MethodKind.Ordinary:
                    var parameters = method.Parameters
                        .Select(p => (p.Name, TypeScriptDefinition.MapType(p.Type)))
                        .ToList();
                    var returnType = method.ReturnsVoid ? "void" : TypeScriptDefinition.MapType(method.ReturnType);
                    methods.Add(new HostObjectMethodInfo(method.Name, parameters, returnType));
                    break;
            }
        }

        var interfaceName = char.ToUpperInvariant(name[0]) + name.Substring(1) + "HostObject";
        return new HostObjectInfo(name, interfaceName, properties, methods);
    }
}
