using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Bermuda.IpcContract.SourceGenerator;

internal sealed record CommandInfo(string Name, string Input, string Output, string Description);

internal sealed record TypeDefinition(string Name, string Body);

/// <summary>An <c>[IpcType]</c> enum — becomes a TS string-literal union of its lowercased member names.</summary>
internal sealed record EnumDefinition(string Name, IReadOnlyList<string> Members);

/// <summary>One public property on an <c>[IpcHostObject]</c> class — becomes a promise-returning getter in TS.</summary>
internal sealed record HostObjectPropertyInfo(string Name, string Type);

/// <summary>One public method on an <c>[IpcHostObject]</c> class — becomes a promise-returning method in TS.</summary>
internal sealed record HostObjectMethodInfo(string Name, IReadOnlyList<(string Name, string Type)> Parameters, string ReturnType);

/// <summary>An <c>[IpcHostObject("name")]</c> class, reflected down to its script-visible surface.</summary>
internal sealed record HostObjectInfo(
    string Name,
    string InterfaceName,
    IReadOnlyList<HostObjectPropertyInfo> Properties,
    IReadOnlyList<HostObjectMethodInfo> Methods);

/// <summary>Maps C# record types and host-object classes to TypeScript and assembles the definition file.</summary>
internal static class TypeScriptDefinition
{
    private const string Header =
        "// <auto-generated>\n" +
        "//  Generated by Bermuda.IpcContract.SourceGenerator. Do not edit.\n" +
        "//  Source of truth: the [IpCommand] / [IpcHostObject] attributes in src/Bermuda.IpcContract\n" +
        "//  and the [IpcHostObject] classes they mark (e.g. src/Bermuda/WindowScriptHost.cs).\n" +
        "// </auto-generated>\n\n";

    public static string Build(
        IReadOnlyList<CommandInfo> commands,
        IReadOnlyList<TypeDefinition> types,
        IReadOnlyList<EnumDefinition> enums,
        IReadOnlyList<HostObjectInfo> hostObjects)
    {
        var sb = new StringBuilder(Header);

        foreach (var type in types)
        {
            sb.Append("export interface ").Append(type.Name).Append(" {\n");
            sb.Append(type.Body);
            sb.Append("}\n\n");
        }

        foreach (var @enum in enums)
        {
            var members = string.Join(" | ", @enum.Members.Select(m => $"'{m}'"));
            sb.Append("export type ").Append(@enum.Name).Append(" = ").Append(members).Append(";\n\n");
        }

        foreach (var hostObject in hostObjects)
        {
            sb.Append("export interface ").Append(hostObject.InterfaceName).Append(" {\n");

            foreach (var property in hostObject.Properties)
            {
                sb.Append("  readonly ").Append(property.Name).Append(": Promise<").Append(property.Type).Append(">;\n");
            }

            foreach (var method in hostObject.Methods)
            {
                var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Name}: {p.Type}"));
                sb.Append("  ").Append(method.Name).Append('(').Append(parameters).Append("): Promise<").Append(method.ReturnType).Append(">;\n");
            }

            sb.Append("}\n\n");
        }

        if (commands.Count > 0)
        {
            sb.Append("export interface IpcMethods {\n");
            sb.Append("  invoke: <T>(command: string) => Promise<T>;\n");
            AppendNamespace(sb, BuildNamespace(commands), 1);
            sb.Append("}\n\n");
        }

        if (hostObjects.Count > 0)
        {
            sb.Append("export interface IpcHostObjects {\n");
            foreach (var hostObject in hostObjects)
            {
                sb.Append("  ").Append(hostObject.Name).Append(": ").Append(hostObject.InterfaceName).Append(";\n");
            }
            sb.Append("}\n");
        }

        return sb.ToString();
    }

    private static NamespaceNode BuildNamespace(IReadOnlyList<CommandInfo> commands)
    {
        var root = new NamespaceNode();
        foreach (var command in commands)
        {
            var segments = command.Name.Split('.');
            var node = root;
            for (var i = 0; i < segments.Length - 1; i++)
            {
                node = node.Children(segments[i]);
            }

            node.Leaves.Add((segments[segments.Length - 1], Signature(command)));
        }

        return root;
    }

    private static void AppendNamespace(StringBuilder sb, NamespaceNode node, int depth)
    {
        var pad = new string(' ', depth * 2);

        // Namespace-less commands, e.g. "ping".
        foreach (var (name, signature) in node.Leaves.OrderBy(x => x.Name, System.StringComparer.Ordinal))
        {
            sb.Append(pad).Append(Escape(name)).Append(": ").Append(signature).Append(";\n");
        }

        // Nested namespaces.
        foreach (var (name, child) in node.ChildrenMap.OrderBy(x => x.Key, System.StringComparer.Ordinal))
        {
            sb.Append(pad).Append(Escape(name)).Append(": {\n");
            AppendNamespace(sb, child, depth + 1);
            sb.Append(pad).Append("};\n");
        }
    }

    private static string Signature(CommandInfo command)
    {
        var parameter = command.Input == "undefined" ? "" : $"payload: {command.Input}, ";
        var result = command.Output == "void" ? "Promise<void>" : $"Promise<{command.Output}>";
        return $"({parameter}) => {result}";
    }

    private static string Escape(string name) => name.Replace("\"", "\\\"");

    /// <summary>Renders a C# record as a TypeScript interface body (indented, semicoloned).</summary>
    public static string MapRecord(INamedTypeSymbol record)
    {
        var properties = record.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .OrderBy(p => p.Name, System.StringComparer.Ordinal);

        var sb = new StringBuilder();
        foreach (var property in properties)
        {
            sb.Append("    ")
              .Append(CamelCase(property.Name))
              .Append(": ")
              .Append(MapType(property.Type))
              .Append(";\n");
        }

        return sb.ToString();
    }

    /// <summary>Reads a C# enum's member names, lowercased, in declaration order (not sorted — matches C# reading order).</summary>
    public static IReadOnlyList<string> MapEnum(INamedTypeSymbol enumType) =>
        enumType.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.ConstantValue is not null)
            .Select(f => CamelCase(f.Name))
            .ToList();

    /// <summary>Maps a C# type to its TypeScript equivalent. Used for both record properties and host-object members.</summary>
    internal static string MapType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
            return "ReadonlyArray<" + MapType(array.ElementType!) + ">";

        if (type is INamedTypeSymbol { IsGenericType: true } named && named.OriginalDefinition.Name == "Nullable")
            return MapType(named.TypeArguments[0]) + " | null";

        // SpecialType, not string-matching ToDisplayString(): FullyQualifiedFormat
        // renders primitives as C# keywords ("bool", "int"), not "global::System.Boolean".
        switch (type.SpecialType)
        {
            case SpecialType.System_Int16:
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_UInt16:
            case SpecialType.System_UInt32:
            case SpecialType.System_UInt64:
            case SpecialType.System_Single:
            case SpecialType.System_Double:
            case SpecialType.System_Decimal:
                return "number";

            case SpecialType.System_Boolean:
                return "boolean";

            case SpecialType.System_String:
            case SpecialType.System_DateTime:
                return "string";

            case SpecialType.System_Object:
                return "unknown";
        }

        // DateTimeOffset/Guid aren't SpecialType members; check by fully qualified name.
        var fq = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (fq is "global::System.DateTimeOffset" or "global::System.Guid")
            return "string";

        // Any other named type is assumed to be another generated interface.
        return type.Name;
    }

    private static string CamelCase(string name)
    {
        if (name.Length == 0 || char.IsLower(name[0]))
            return name;

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private sealed class NamespaceNode
    {
        private readonly Dictionary<string, NamespaceNode> _children = new(System.StringComparer.Ordinal);
        public List<(string Name, string Signature)> Leaves { get; } = new();

        public Dictionary<string, NamespaceNode> ChildrenMap => _children;

        public NamespaceNode Children(string name) =>
            _children.TryGetValue(name, out var existing) ? existing : _children[name] = new NamespaceNode();
    }
}
