// <auto-generated>
//  Generated by Bermuda.IpcContract.SourceGenerator. Do not edit.
//  Source of truth: the [IpCommand] / [IpcHostObject] attributes in src/Bermuda.IpcContract
//  and the [IpcHostObject] classes they mark (e.g. src/Bermuda/WindowScriptHost.cs).
// </auto-generated>

export interface HostResponse {
    id: string;
    result: unknown;
}

export interface IpcRequest {
    command: string;
    id: string;
    payload: unknown;
}

export interface PingResult {
    pong: boolean;
}

export interface WindowBounds {
    height: number;
    left: number;
    top: number;
    width: number;
}

export interface WindowStateSnapshot {
    bounds: WindowBounds;
    isFocused: boolean;
    isMaximized: boolean;
    isMinimized: boolean;
}

export type TaskbarProgressState = 'none' | 'indeterminate' | 'normal' | 'error' | 'paused';

export interface WindowControllerHostObject {
  readonly IsMaximized: Promise<boolean>;
  readonly IsMinimized: Promise<boolean>;
  readonly IsFocused: Promise<boolean>;
  readonly Left: Promise<number>;
  readonly Top: Promise<number>;
  readonly Width: Promise<number>;
  readonly Height: Promise<number>;
  Minimize(): Promise<void>;
  Maximize(): Promise<void>;
  Restore(): Promise<void>;
  ToggleMaximize(): Promise<void>;
  Close(): Promise<void>;
  Resize(width: number, height: number): Promise<void>;
  Move(x: number, y: number): Promise<void>;
  Show(): Promise<void>;
  Hide(): Promise<void>;
  SetOverlayIcon(iconPng: string, description: string): Promise<void>;
  ClearOverlayIcon(): Promise<void>;
  SetProgressState(state: string): Promise<void>;
  SetProgressValue(value: number): Promise<void>;
}

export interface IpcMethods {
  invoke: <T>(command: string) => Promise<T>;
  ping: () => Promise<PingResult>;
}

export interface IpcHostObjects {
  windowController: WindowControllerHostObject;
}
